[platformio]
src_dir = firmware/ESP32CAMGatos

[env:esp32cam]
platform = espressif32@6.13.0
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DCORE_DEBUG_LEVEL=1

