[platformio]
src_dir = firmware/XIAOS3Gatos

[env:xiao_esp32s3_sense]
platform = espressif32@6.13.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.f_cpu = 240000000L
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
